### ISSUE TITLE
Compilation Instructions

### ISSUE THREAD

**Issue by jasonbohlinger** [pescalette/pulse#1]
Although you mentioned that the current code generation is not complete and there are some issues to the indentation of certain lines, what libraries will be required? Are there additional instructions for compilation and execution of the generated_code.py file from your website?

**Comment by ghost** [comment]
I started to work on this in 6f72e0e465fb072b3b73f13972ace82ca5e601cc , I have a working arm in the simulation and am working on moving my blocks to choose one of the working arms to simulate in webots. To answer your question you will need to download [webots](https://cyberbotics.com/#download) then save the python file into the correct controller directory, then open the webots world and hit play. Inside of python there are a few dependencies that i will add to a dependencies file for a quick pip install of all of them.

This seems like a long process so hopefully i can contain all of this into a "quickstart" batch file that will handle all of that.

**Comment by ghost** [comment]
Closed with addition of #5.
This should be sufficient in getting started with the project.
