### ISSUE TITLE
Issues with test.py

### ISSUE THREAD

**Issue by wspropst** [pescalette/pulse#7]
Here are some observations and potential concerns regarding these test cases:

- **Infinite Position**: Setting the position of a motor to `float('inf')` might be intended to rotate the motor continuously without stopping. This could be a test to ensure the motors can run indefinitely, but in a practical scenario, motors would have physical limits and control algorithms to reach certain positions.

- **Uniform Velocity**: All motors are set to the same velocity. This may not reflect real-world scenarios where different motors might need to move at different speeds to achieve smooth and coordinated movement.

- **No Loop or Condition**: The script sets the position and velocity of the motors but does not contain a control loop or any condition to stop the motors. In a real robot control script, you would expect to see some kind of loop that continues to check sensor inputs and adjust motor commands accordingly.

- **No Error Handling**: There is no error checking to ensure that the motors have been correctly retrieved and that setting the position and velocity was successful.

- **Testing Strategy**: If this is meant to be a test script, it would be beneficial to include assertions or checks to ensure the motors behave as expected after these commands are issued.

- **Timestep Usage**: The `timestep` variable is defined but not used. Typically, you would pass this variable to the `robot.step(timestep)` method within a loop to proceed to the next simulation step.

- **No Gradual Acceleration**: Directly setting a velocity without acceleration might not be suitable for all motors, especially if they are starting from a standstill, as this could cause a jerk in motion.

**Comment by ghost** [comment]
The addition of this was an oversight and was just used to test the motors during development. Removed `test.py` in e1a337ef1e98711a01d61d90d0edfcd916ef20c7.
