### ISSUE TITLE
Motor names and waypoint block optional speed

### ISSUE THREAD

**Issue by MilesR8** [pescalette/pulse#8]
The use of naming motors is unclear as named motor variables are not used and instead all functions are called on a more general "motor" variable. I am not sure if this variable has all motor names saved to it so it is a bit unclear. The waypoint optional speed parameter block does not add any code generation. I think if you are to save many motors in the code generation it would get a bit complicated knowing which motor to send an action to if they are independent of each other. If they are independent, I think it would be simpler to remove the motor name block and instead a field to the initialization block to create one motor only and call all functions on that motor.

**Comment by MilesR8** [comment]
You are also allowed to add motor name to the main program which I believe you might not want to do.

**Comment by ghost** [comment]
In the current design (as of 4f5a020), I have abstracted away the need for users to manage individual motor names in the Blockly interface. This abstraction is aimed at reducing complexity and potential for error that might come from managing multiple motors with independent names. Instead, we handle motor names programmatically in the backend, allowing users to focus on higher-level robot actions without worrying about the specifics of motor control (at least not for the default robot).
